name: deepinvhessian
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11.5
  - pip
  - numpy<2.0
  - scipy
  - matplotlib
  - ipython
  - jupyter
  - tqdm
  - scikit-image
  - pip:
      - torch==2.1.2 --index-url https://download.pytorch.org/whl/cu118
      - torchvision==0.16.2 --index-url https://download.pytorch.org/whl/cu118
      - pylops
      - deepwave
      - opencv-python
      - setuptools-scm